server:
  port: 7799

file:
  directory: D:/tmp/latest/
  corn: 0 17 11 1/1 * ?
  suffix: .txt
  queue: everyday_file
  ip: 124.221.21.212
  user: ubuntu
  password: qwerpoiu147369@!
  port: 22
  filePath: /home/gy/data/latest/



